### ISSUE TITLE
Ideas for The Game

### ISSUE THREAD

**Issue by VirdanTheBurden** [cat-dev-group/pyweek-33#2]
Hey there! Instead of putting all of our thoughts in our discord channel, I've decided to focus the conversation here on Github, seeing as it's easier to follow a thread-like format rather than an open chatroom. To that end... post your ideas here!

**Comment by VirdanTheBurden** [comment]
@AbooMinister25, @Evorage0, and I were discussing this late last night, but we came up with an idea involving the Prisoner's Dilemma argument.

For those who don't know what that is, it's basically a study on how the mind operates in a situation where you can cooperate or betray another human being. The premise goes like this:
- You have two people that have two options: cooperation or betrayal
- If both parties cooperate, they both get 3 points.
- If both parties defect, they both get 1 point.
- If one defects and the other cooperates, the defector gets 5 points and the cooperator gets nothing.

The idea involving this was to have a sort of turn-based game based on this premise where "points" is actually damage, and you had to do boss fights to either:
- Stall for time and befriend your opponent
- or defeat your opponent by getting them to 0 health

Front mentioned mirror dimensions which is also a great idea, so if any of you would like to elaborate on that, feel free to!

**Comment by Shom770** [comment]
Regarding the mirror dimension:
An RPG where your goal is to defeat a boss, but you have to keep working towards different tasks to defeat that boss. The moment you lose the balance between preparing and working towards different tasks, the mirror dimension begins to pop up on your screen. The mirror dimension holds the evil counterpart of everyone, and works with the boss. First, it'll be a flicker that appears for a bit. After the flicker, you become more vulnerable to the mirror dimension. The time the mirror dimension appears grows longer and longer till it takes over and if it takes over or you lose to the boss, you lose the game.

**Comment by Objectivitix** [comment]
@Shom770 The idea is certainly innovative, but what do you mean by "losing the balance"? Also, how does the mirror dimension manifest itself? As a part of the game window?

**Comment by Objectivitix** [comment]
Here's my idea for the theme. I think it can work out, although I'm not sure if this has already been done before - I'd like our game to have an original premise.

A platformer where each level is split in two - the top half and the bottom half. The player moves through the levels' top half, trying to reach an end goal (exit, flag, whatever). However, their movements are copied by an evil twin, in the bottom half. Using a normal approach to beat the level will result in the evil twin walking on buttons/triggers that makes the player lose. The player needs to find a way to stagger the movement of the two characters (by utilizing top-bottom layout differences) in order to win. In later levels, the player might also need to use the evil twin to unlock certain parts of a level.

Simplest example (green = finish, red = death, blue = top-bottom split):
![](https://user-images.githubusercontent.com/79152594/159176295-def6fa8b-58aa-43ef-b194-0ae3107b6cea.png)

We can really go in any direction with this platformer idea, but we must find some way to spice it up to make it unique.

**Comment by VirdanTheBurden** [comment]
This has been done before, yeah. But it *is* fun regardless. Ok, let's put that down.

**Comment by Shom770** [comment]
> @Shom770 The idea is certainly innovative, but what do you mean by "losing the balance"? Also, how does the mirror dimension manifest itself? As a part of the game window?

"losing the balance" means that if you don't complete a task by a certain night, you start to 'lose the balance' per se. To be honest, there doesn't have to be an epic boss fight, it could just be a series of tasks to get off a certain planet or situation or something.

The mirror dimension manifests itself as part of the game window, yes.

**Comment by Oreo4102004** [comment]
My idea is based on wordle and only one player is will play it but,

window will be split into two
one is your game window , other window will also have a game running but it will unintentionally be controlled by us
The game mechanics will choose winning words for both game instances such that those words are closer to each other 
everytime we enter a word, that word will also be entered in the other game instance
the color hintings will remain the same 
to win the game we have to win it first before the next window wins

**Comment by brad90four** [comment]
> However, their movements are copied by an evil twin

I had a similar idea, where the evil twin is copying the player's movements / input. I think it is pretty good idea, even if there is a chance that the premise is copied by other teams.

**Comment by Objectivitix** [comment]
@Oreo4102004 Double wordle, very interesting!

**Comment by Kronifer** [comment]
> RE: @Objectivitix 's idea:
> > However, their movements are copied by an evil twin
> 
> I had a similar idea, where the evil twin is copying the player's movements / input. I think it is pretty good idea, even if there is a chance that the premise is copied by other teams. 

Makes me think of a section of Celeste
